/**
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 * Class Name      : House
 * Author          : <YourName>
 * Created Date    : May 23, 2026
 * Last Modified By: <YourName>
 * Last Modified On: May 23, 2026
 * Description     : This class implements for......
 *  
 * Change History  :
 *  Date          │   Author     │   Change
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 *  May 23, 2026  │ <YourName>   │ Initial version
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 */

public class House {
	public string OwnerName;
	public Integer noOfRooms ;
	public boolean hasParking ;

	public void openDoor() {
		
	}
	public void closeDoor() {
		
	}
	public void showHouseDetails() {
		System.debug('ownername --> '+ownername+' noofrooms --> '+noOfRooms+ ' hasparking --> '+hasParking );
	}	

}